### ISSUE TITLE
Have we considered supporting required flag?

### ISSUE THREAD

**Issue by neverchanje** [desertbit/grumble#29]
```
	rootCmd.AddCommand(&grumble.Command{
		Name: "add",
		Help: "add a duplications to the table",
		Run: func(c *grumble.Context) error {
			if c.Flags.String("cluster") == "" {
				return fmt.Errorf("cluster cannot be empty")
			}
			return executor.AddDuplication(pegasusClient, useTable, c.Flags.String("cluster"), c.Flags.Bool("freezed"))
		},
		Flags: func(f *grumble.Flags) {
			f.String("c", "cluster", "", "the destination where the source data is duplicated")
			f.Bool("f", "freezed", false, "whether to freeze replica GC when duplication created")
		},
	})
```

Hi, I'm developing a CLI tool using the fantastic grumble library. I see we can not declare a flag without giving it a default value, like a [required flag](https://github.com/spf13/cobra#required-flags).

I'd suggest introducing an API for `grumble.Flags`, it could help much simplify the boilerplate code of empty flag check.

```go
		Flags: func(f *grumble.Flags) {
			f.String("c", "cluster", "", "the destination where the source data is duplicated")
			f.Bool("f", "freezed", false, "whether to freeze replica GC when duplication created")

                        f.MarkFlagRequired("cluster")
		},
```

What do you think?

**Comment by skaldesh** [comment]
While implementing #25 to add argument support, I thought a lot about this as well. Should args be mandatory? What about flags?  
I think one sensible conclusion I got from it was that flags seem, at least to me, always more like optional stuff that you **could** adjust, but do not **have to**. Args on the other hands seem like something that the program always requires in order to correctly function.  

Would it be sensible for you to either keep specifying a sensible default (in your case `"cluster"` could point to the current working directory, for example) or to convert your flag to an argument?

**Comment by neverchanje** [comment]
If this library provides only the flags for user input, I would prefer to "required flags". But given your incomplete works of args, it's OK for me to use args to replace flags not optional.

**Comment by neverchanje** [comment]
I'm much expecting your work on arguments. Let me know if there's anything I could help :) Since your opinion on flags is acceptable to me, I close this issue now.

**Comment by skaldesh** [comment]
I hope it gets merged soon. You could ping @r0l1 and let him know, that you need the features as well :)

Btw, #25 more improves argument support, as args can already be used by setting `AllowArgs: true` and accessing them with `context.Args[0]`. In my PR I add typed args (much similar to how flags work) and some other convenience stuff. So if you want to convert your flag to arg, you can do that already
